type EnvType = {
  ACCOUNT_SUFFIX: string;
  NEAR_NETWORK_ID: string;
  NEAR_NODE_URL: string;
  ROKETO_CONTRACT_NAME: string;
  WALLET_URL: string;
  PUBLIC_URL: string;
  PRICE_ORACLE_CONTRACT_NAME: string,
  PRICE_ORACLE_SOURCE_ID: string,
  WNEAR_ID: string;
  WEB_API_URL: string;
  COMMIT_HASH: string
  BUILD_TIME: string | null
}

export const env = {
  ACCOUNT_SUFFIX: process.env.REACT_APP_NEAR_ACCOUNT_SUFFIX,
  NEAR_NETWORK_ID: process.env.REACT_APP_NEAR_NETWORK_ID,
  NEAR_NODE_URL: process.env.REACT_APP_NEAR_NODE_URL,
  ROKETO_CONTRACT_NAME: process.env.REACT_APP_ROKETO_CONTRACT_NAME,
  WALLET_URL: process.env.REACT_APP_WALLET_URL,
  PUBLIC_URL: process.env.PUBLIC_URL,
  PRICE_ORACLE_CONTRACT_NAME: process.env.REACT_APP_PRICE_ORACLE_CONTRACT_NAME,
  PRICE_ORACLE_SOURCE_ID: process.env.REACT_APP_PRICE_ORACLE_SOURCE_ID,
  WNEAR_ID: process.env.REACT_APP_WNEAR_ID,
  WEB_API_URL: process.env.REACT_APP_WEB_API_URL,
  COMMIT_HASH: process.env.COMMIT_HASH ?? 'development',
  BUILD_TIME: process.env.BUILD_TIME ?? null,
} as EnvType;

export const GAS_SIZE = "200000000000000";
