export const env = {
  ACCOUNT_SUFFIX: process.env.REACT_APP_NEAR_ACCOUNT_SUFFIX,
  NEAR_NETWORK_ID: process.env.REACT_APP_NEAR_NETWORK_ID,
  NEAR_NODE_URL: process.env.REACT_APP_NEAR_NODE_URL,
  CONTRACT_NAME: process.env.REACT_APP_CONTRACT_NAME,
  WALLET_URL: process.env.REACT_APP_WALLET_URL,
};
