name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          #framework: cypress
          #tests: "./cypress/integration/tests/*.js"
          #token: ${{ secrets.GITHUB_TOKEN }}
          has-tests-label: true
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2