name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          has-tests-label: true
      - name: Cypress run
        uses: cypress-io/github-action@v2