name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          has-tests-label: true
          wait-on-timeout: 120
          record: false
          parallel: false
          start: PORT=8080 yarn start 
          wait-on: 'http://localhost:8080'
