name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node-18-modules-${{ hashFiles('yarn.lock') }}

      - name: Install deps 🔧
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --silent

      - name: Check testIds
        working-directory: .
        run: yarn testIds:check

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 120
          record: false
          parallel: false
          start: |
            yarn build
            yarn preview
          wait-on: 'http://localhost:3000'
