name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 120
          record: false
          parallel: false
          start: yarn start --port 3000
          wait-on: 'http://localhost:3000'
